OpenAI
deep-foundation/sdk pull request #51
Opened 2023-02-21 16:11 UTC by flakeed

feature/add-handler-openai

2023-02-21 16:16 UTC, FreePhoenix888 requested changes

2023-02-21 16:16 UTC, FreePhoenix888 commented on imports/handler-openai/openai-handler.js
> +    const dotenv = require('dotenv');
It is better to move this import above out of this function

2023-02-21 16:16 UTC, FreePhoenix888 commented on imports/handler-openai/openai-handler.js
> +    const triggerTypeLinkId=(PACKAGE_NAME, "openAiRequestTypeLinkId")
Remove this line

2023-02-21 16:16 UTC, FreePhoenix888 commented on imports/handler-openai/openai-handler.js
> +    const code = fs.readFileSync('packages/sdk/imports/handler-openai/value-handler.js', {encoding: 'utf-8'});
You can inline this variable. I mean use its value right where it is used

2023-02-21 16:16 UTC, FreePhoenix888 commented on imports/handler-openai/openai-handler.js
> +                from_id: userLinkId,
```suggestion
                from_id: deep.linkId,
```

2023-02-21 16:16 UTC, FreePhoenix888 commented on imports/handler-openai/openai-handler.js
> +    const { data: [{ id: openAiApiKeyLinkId, }] } = await deep.insert({
```suggestion
    const { data: [{ id: openAiApiKeyTypeLinkId, }] } = await deep.insert({
```

2023-02-21 16:16 UTC, FreePhoenix888 commented on imports/handler-openai/openai-handler.js
> +    const { data: [{ id: openAiApiKeyTypeLinkId }] } = await deep.insert({
```suggestion
    const { data: [{ id: openAiApiKeyLinkId }] } = await deep.insert({
```

2023-02-21 16:16 UTC, FreePhoenix888 commented on imports/handler-openai/openai-handler.js
> +        type_id: openAiApiKeyLinkId,
```suggestion
        type_id: openAiApiKeyTypeLinkId,
```

2023-02-21 16:16 UTC, FreePhoenix888 commented on imports/handler-openai/openai-handler.js
> +                from_id: userLinkId,
```suggestion
                from_id: deep.linkId,
```

2023-02-21 16:16 UTC, FreePhoenix888 commented on imports/handler-openai/openai-handler.js
> +                                from_id: triggerTypeLinkId,
```suggestion
                                from_id: openAiRequestTypeLinkId,
```

2023-02-21 16:16 UTC, FreePhoenix888 commented on imports/handler-openai/openai-handler.js
> +                value: code,
```suggestion
                value: fs.readFileSync('packages/sdk/imports/openai/requestHandler.js', {encoding: 'utf-8'}),
```

2023-02-21 16:33 UTC, FreePhoenix888 requested changes

2023-02-21 16:33 UTC, FreePhoenix888 commented on imports/openai/install-package.js
> +                    string: {data: {value: fileWithCodeOfHandlerName}},
```suggestion
                    string: {data: {value: "OpenAiRequestHandlerCode"}},
```

2023-02-21 16:33 UTC, FreePhoenix888 commented on imports/openai/install-package.js
> +                                string: {data: {value: handlerName}},
```suggestion
                                string: {data: {value: "OpenAiRequestHandler"}},
```

2023-02-21 16:33 UTC, FreePhoenix888 commented on imports/openai/install-package.js
> +                                            string: {data: {value: handleName}},
```suggestion
                                            string: {data: {value: "HandleOpenAiRequest"}},
```

2023-02-21 16:33 UTC, FreePhoenix888 commented on imports/openai/install-package.js
> +const dotenv = require('dotenv');
```suggestion
require('dotenv').config();
```

2023-02-21 16:33 UTC, FreePhoenix888 commented on imports/openai/openAiRequestInsertHandler.js
> +        id: openAiRequestLink
```suggestion
        id: openAiRequestLink.to_id
```

2023-02-21 17:00 UTC, FreePhoenix888 requested changes

2023-02-21 17:00 UTC, FreePhoenix888 commented on imports/openai/install-package.js
> +    const handleName = "HandleName";
```suggestion
```

2023-02-21 17:00 UTC, FreePhoenix888 commented on imports/openai/requestHandler.js
> +    })
```suggestion
    const {data: [apiKeyLink]} = await deep.select({
        type_id: openAiApiKeyTypeLinkId,
        in: {
            type_id: containTypeLinkId,
            from_id: triggeredByLinkId
        }
    })
    if(!apiKeyLink){
      throw new Exception(`A link with type ##${openAiApiKeyTypeLinkId} is not found`)
    }
    if(!apiKeyLink.value?.value){
      throw new Exception(`##${apiKeyLink.id} must have a value`)
    }
```

2023-02-22 10:38 UTC, FreePhoenix888 requested changes

2023-02-22 10:38 UTC, FreePhoenix888 commented on imports/openai/openai-install.tsx
> +import { DeepClient } from "@deep-foundation/deeplinks/imports/client";
Remove this file

2023-02-22 10:38 UTC, FreePhoenix888 commented on imports/openai/install-package.js
> +async function insertOpenAiHandler(){
```suggestion
async function installOpenAiPackage({deep}: {deep: DeepClient}){
```

2023-02-22 10:38 UTC, FreePhoenix888 commented on imports/openai/install-package.js
> +    const deep = new DeepClient({ deep: guestDeep, ...admin });
```suggestion
```

2023-02-22 10:38 UTC, FreePhoenix888 commented on imports/openai/install-package.js
> +    const installPackage = async () => {
Move content of this function outside of this function and delete this function

2023-02-22 10:57 UTC, FreePhoenix888 requested changes

2023-02-22 10:57 UTC, FreePhoenix888 commented on pages/index.tsx
> +import { insertPackageToDeep as insertDevicePackageToDeep } from '../imports/device/insert-package-to-deep';
```suggestion
import { insertPackageToDeep as insertOpenAiPackageToDeep } from '../imports/openai/insert-package-to-deep';
```

2023-02-22 10:57 UTC, FreePhoenix888 commented on pages/index.tsx
> +import { PACKAGE_NAME as DEVICE_PACKAGE_NAME } from '../imports/device/package-name';
```suggestion
import { PACKAGE_NAME as OPENAI_PACKAGE_NAME } from '../imports/openai/package-name';
```

2023-02-22 10:57 UTC, FreePhoenix888 commented on pages/index.tsx
> +      if (!await getIsPackageInstalled({deep, packageName: DEVICE_PACKAGE_NAME})) {
```suggestion
      if (!await getIsPackageInstalled({deep, packageName: OPENAI_PACKAGE_NAME})) {
```

2023-02-22 10:57 UTC, FreePhoenix888 commented on pages/index.tsx
> +        await insertDevicePackageToDeep({ deep });
```suggestion
        await insertOpenAiPackageToDeep({ deep });
```

2023-02-22 11:36 UTC, FreePhoenix888 requested changes

2023-02-22 11:36 UTC, FreePhoenix888 commented on imports/openai/install-package.ts
> +    const handleOperationLinkId = await deep.id('@deep-foundation/core', "HandleInsert" /* | HandleUpdate | HandleDelete */);
```suggestion
    const handleInsertLinkId = await deep.id('@deep-foundation/core', "HandleInsert");
```

2023-02-22 11:36 UTC, FreePhoenix888 commented on imports/openai/install-package.ts
> +    const packageLinkId = await deep.id('@deep-foundation/core', "Package");
```suggestion
    const packageTypeLinkId = await deep.id('@deep-foundation/core', "Package");
```

2023-02-22 11:36 UTC, FreePhoenix888 commented on imports/openai/install-package.ts
> +
```suggestion
    const { data: [{ id: packageLinkId }] } = await deep.insert({
    type_id: packageTypeLinkId,
    string: { data: { value: PACKAGE_NAME } },
    in: { data: [
      {
        type_id: containTypeLinkId,
        from_id: deep.linkId
      },
    ] },
    out: { data: [
      {
        type_id: joinTypeLinkId,
        to_id: await deep.id('deep', 'users', 'packages'),
      },
      {
        type_id: joinTypeLinkId,
        to_id: await deep.id('deep', 'admin'),
      },
    ] },
  });
  
```

2023-02-22 11:36 UTC, FreePhoenix888 commented on imports/openai/install-package.ts
> +import * as fs from "fs";
```suggestion
import * as fs from "fs";
import {PACKAGE_NAME} from "./package-name";
```

2023-02-22 11:36 UTC, FreePhoenix888 commented on imports/openai/install-package.ts
> +    const supportsJsLinkId = await deep.id('@deep-foundation/core', "dockerSupportsJs" /* | "plv8SupportsJs" */);
```suggestion
    const dockerSupportsJsLinkId = await deep.id('@deep-foundation/core', "dockerSupportsJs");
```

2023-02-22 11:36 UTC, FreePhoenix888 commented on imports/openai/install-package.ts
> +                                type_id: handleOperationLinkId,
```suggestion
                                type_id: handleInsertLinkId,
```

2023-02-22 11:36 UTC, FreePhoenix888 commented on imports/openai/install-package.ts
> +                    from_id: supportsJsLinkId,
```suggestion
                    from_id: suppodockerSupportsJsLinkIdtsJsLinkId,
```

2023-02-22 11:36 UTC, FreePhoenix888 commented on imports/openai/requestHandler.js
> +async ({data: {newLink:openAiRequestLink,triggeredByLinkId},deep}) => {
Rename this file to `request-handler.js`

2023-02-22 11:36 UTC, FreePhoenix888 commented on imports/openai/install-package.ts
> +                value: fs.readFileSync('packages/sdk/imports/openai/requestHandler.js', {encoding: 'utf-8'}),
```suggestion
                value: fs.readFileSync('packages/sdk/imports/openai/request-handler.js', {encoding: 'utf-8'}),
```

2023-02-22 15:08 UTC, FreePhoenix888 requested changes

2023-02-22 15:08 UTC, FreePhoenix888 commented on imports/openai/install-package.ts
> +    });
Move functionality related to a user to Buttons. Create them on pages/openai.tsx

2023-02-22 15:08 UTC, FreePhoenix888 commented on imports/openai/install-package.ts
> +    });
Do not forget to do this not only to these lines but in the code below

2023-02-22 15:08 UTC, FreePhoenix888 commented on pages/index.tsx
> +import { installOpenAiPackage as insertOpenAiPackageToDeep } from '../imports/openai/install-package';
```suggestion
import { installPackage as installOpenAiPackage } from '../imports/openai/install-package';
```

2023-02-22 15:08 UTC, FreePhoenix888 commented on pages/index.tsx
> +        await insertOpenAiPackageToDeep({ deep });
```suggestion
        await installOpenAiPackage ({ deep });
```

2023-02-22 18:14 UTC, FreePhoenix888 requested changes

2023-02-22 18:14 UTC, FreePhoenix888 commented on pages/openai.tsx
> +            type_id: await deep.id(PACKAGE_NAME, "OpenAiRequest"),
```suggestion
            type_id: await deep.id(PACKAGE_NAME, "OpenAiApiKey"),
```

2023-02-24 06:03 UTC, FreePhoenix888 requested changes

2023-02-24 06:03 UTC, FreePhoenix888 commented on package.json
> +    "fs": "0.0.1-security",
```suggestion
```

2023-02-24 06:03 UTC, FreePhoenix888 commented on imports/openai/install-package.ts
> +}
```suggestion
}

installPackage()
```

2023-02-24 06:03 UTC, FreePhoenix888 commented on pages/index.tsx
> +
```suggestion
```

2023-02-24 06:03 UTC, FreePhoenix888 commented on pages/index.tsx
> +import { PACKAGE_NAME as OPENAI_PACKAGE_NAME } from '../imports/openai/package-name';
```suggestion
```

2023-02-24 12:29 UTC, FreePhoenix888 requested changes

2023-02-24 12:29 UTC, FreePhoenix888 commented on imports/openai/request-handler.js
> +    const CircularJSON = require('circular-json');
```suggestion
```

2023-02-24 12:29 UTC, FreePhoenix888 commented on imports/openai/request-handler.js
> +    })
```suggestion
    const {data: [linkWithStringValue]} = await deep.select({
        id: openAiRequestLink.to_id
    })
    if(!linkWithStringValue.value?.value){
        throw new Error(`##${linkWithStringValue.id} must have a value`)
    }
    const openAiPrompt = linkWithStringValue.value.value
```

2023-03-12 10:12 UTC, FreePhoenix888 commented
https://discord.com/channels/739430470345031692/997089753356845117/1083777312102817863

2023-03-12 10:12 UTC, FreePhoenix888 commented
в пакетах, которые ожидают какой-либо токен или что-то подобное законтеиненное в пользователя - нужно подредактировать это место. Юзер  может иметь законтеиненными сколько угодно таких связей. А что бы понять какой именно использовать - нужно искать связь Uses\w+
К примеру я сейчас в пуш нотификациях поменяю логику таким образом
До: ищу ServiceAccount
После: ищу ServiceAccount, на который юзер указывает с помощью связи UsesServiceAccount

2023-03-22 09:00 UTC, FreePhoenix888 requested changes

2023-03-23 22:46 UTC, Konard commented on imports/openai/install-package.ts
> +
No we do not need to do it for this package.

2023-03-23 22:46 UTC, Konard commented on imports/openai/install-package.ts
> +    });
We should keep this package as is.

2023-04-11 16:32 UTC, closed without merging